loadPhotos([
  "photo/photo01.jpg",
  "photo/photo02.jpg",
  "photo/photo03.jpg",
  "photo/photo04.jpg",
  "photo/photo05.jpg",
  "photo/photo06.jpg",
  "photo/photo07.jpg",
  "photo/photo08.jpg",
  "photo/photo09.jpg"
]);
